runtime:python311

instnace_class: F2

env_variables:
  SECRET_KEY: "1234"
  GOOGLE_CLOUD_PROJECT: "projectID"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances_ 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
  