runtime:python311

instnace_class: F2

env_variables:
  SECRET_KEY: "python -c "import secrets; print(secrets.token_hex(24))""

  GOOGLE_CLOUD_PROJECT: "cloudmart-ecommerce"

  DATABASE_URL: 'mysql+pymysql://cloudmart_user:BigBrain321?!@/cloudmart?unix_socket=/cloudsql/YOUR_CONNECTION_NAME'

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances_ 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

  beta_settings:
    cloud_sql_instances: "cloudmart-ecommerce:europe-west1:cloudmart-sql"
  